[project]
name = "inpost-air"
version = "1.5.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["dacite==1.9.2", "python-slugify==8.0.4"]

[project.optional-dependencies]
dev = ["homeassistant==2025.3.1", "ruff==0.9.9"]
