name: Build and release
on:
    workflow_dispatch:
        inputs:
            dryRun:
                description: Dry run
                default: true
                type: boolean

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write # to be able to publish a GitHub release
            issues: write # to be able to comment on released issues
            pull-requests: write # to be able to comment on released pull requests
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Semantic Release
              id: semantic-release
              uses: cycjimmy/semantic-release-action@v5
              with:
                  dry_run: ${{ github.event.inputs.dryRun == 'true' }}
                  semantic_version: 24.2.8
                  extra_plugins: |
                      @semantic-release/changelog@6.0.3
                      @semantic-release/git@10.0.1
                      @semantic-release/exec@7.0.3
                      @ceski23/semantic-release-hacs@1.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
